### PR TITLE
Added Support for additional Activation functions and their derivatives

### PR DESCRIPTION
**Pull request by Sohammhatre10**
Summary:
This PR adds several new activation functions and their derivatives to the `activation` and `activation_derivative` functions, updates documentation, and enhances unit tests in context to https://github.com/ravin-d-27/PyDeepFlow/issues/15.

Key Changes:
New activation functions have been added to the activation and activation_derivative functions. The new functions are:

```
- PReLU
- ELU
- GELU
- Swish
- SELU
- Softplus
- Mish
- RReLU
- HardSwish
- Softsign
- TanhShrink
- SoftShrink
- HardShrink
```

Additionally, the existing Leaky ReLU function was modified to accept an alpha parameter, and some functions like Hardtanh and Hardsigmoid, which were not explicitly mentioned in the original code, are now included in the list of supported functions.

Testing:
All changes validated with unittest, including edge cases.

### CODE REVIEW

**Comment by Sohammhatre10** [comment]
@ravin-d-27 if this works will you please tag this as ``hacktoberfest-accpeted``
Thanks!

**Comment by Sohammhatre10** [comment]
Didn't get adding the activation functions to model.py as they are being called and the user while running runner.py has the option to enter the activation as ``['relu', 'relu']`` and change according to the ones available. The user can get it from `pydeepflow.activations(required_activation)`. Just tell me if explicit input is required from the user.

**Comment by ravin-d-27** [comment]
Hi @Sohammhatre10 ! Thank you for the PR !
I will try running the `runner.py` by changing the `['relu', 'relu']` into the newly introduced activation functions, and let you know !

**Comment by ravin-d-27** [comment]
Hi @Sohammhatre10 
I tried to run `runner.py` using the new activation functions. 
image

Faced this issue. And I found that there is no `abs()` function in `device.py`. 
image

Your work is great! But can you please add the abs function in `device.py` and make a PR?

**Comment by Sohammhatre10** [comment]
Sure will add `abs` method to device.py

**Pull request closed without merging**
