### PR TITLE
Fixed Error in Batch Normalization Implementation

### PR DESCRIPTION
**Pull request by SujitSakore**
Resolved an issue in the Batch Normalization implementation within the deep learning framework. The error occurred during the normalization process, particularly in calculating the running mean and variance, which affected the stability and performance of the model during training and inference. The fix involved ensuring that the moving averages for the mean and variance were updated correctly based on the batch statistics, allowing for effective normalization of inputs across different layers. This enhancement improves the overall training efficiency and model accuracy.

### CODE REVIEW

**Comment by SujitSakore** [comment]
Hello, @ravin-d-27 I wanted to let you know that I have resolved the issue Fixed Error in Batch Normalization Implementation #32. If there are any changes or further adjustments needed, please let me know. I would appreciate it if you could accept my pull request.

**Comment by ravin-d-27** [comment]
Hi @SujitSakore , thank you! Will check the code and merge the PR soon!

**Comment by ravin-d-27** [comment]
Hi @SujitSakore ! Thank you for the enhancement ! I am merging this PR to main branch !

**Comment by SujitSakore** [comment]
Thank you! @ravin-d-27  Glad to contribute.

**Pull request merged**
