### PR TITLE
Robust Model Evaluation with k-Fold Cross-Validation for Multi-Layer Neural Networks

### PR DESCRIPTION
**Pull request by SujitSakore**
This project implements a robust k-fold cross-validation framework for evaluating Multi-Layer Artificial Neural Networks (ANNs), aimed at enhancing model generalization and mitigating overfitting risks.

The CrossValidator class allows users to specify the number of folds and evaluation metrics, providing a systematic approach to model validation. Key features include:

1.Dynamic Configuration: Users can effortlessly customize the number of folds and performance metrics, catering to various modeling scenarios.
2.Comprehensive Insights: The implementation delivers detailed performance metrics for each fold, enabling thorough analysis and comparison of model efficacy across different subsets of the data.
3.Improved Model Robustness: By training and validating on diverse data segments, the framework fosters a deeper understanding of the model's behavior and its ability to generalize to unseen data.

This initiative not only refines the evaluation process for ANNs but also builds confidence in their deployment across real-world applications, ultimately contributing to the development of more reliable and accurate machine learning models.

### CODE REVIEW

**Comment by SujitSakore** [comment]
Hello @ravin-d-27 I have resolved the issue. If there are any changes or further adjustments needed, please let me know. I would appreciate it if you could accept my pull request.

**Comment by SujitSakore** [comment]
Hello @ravin-d-27 could you please accept my pull request

**Comment by ravin-d-27** [comment]
Hi @SujitSakore ! Will accept your pull request. Sorry for the delay as I was busy with my University Exams.

**Comment by ravin-d-27** [comment]
Hi @SujitSakore , can you please resolve the merge conflicts? I'm unable to merge the PR.

**Comment by SujitSakore** [comment]
hello @ravin-d-27 I have resolve the issue.

**Comment by ravin-d-27** [comment]
Thank you @SujitSakore for your contribution!

**Pull request merged**
